app_restau_quai_antique:
    path: /
    controller: App\Controller\AccueilController::accueil
carte_restau_quai_antique:
    path: /carte
    controller: App\Controller\CarteController::carte
reserver_restau_quai_antique:
    path: /reserver
    controller: App\Controller\ReservationController::reserver
apropos_restau_quai_antique:
    path: /apropos
    controller: App\Controller\AproposController::apropos
utilisateur_inscription:
    path: /inscription
    controller: App\Controller\UtilisateurController::inscription   
utilisateur_connexion:
    path: /connexion
    controller: App\Controller\UtilisateurController::connexion 
utilisateur_deconnexion:
    path: /deconnexion
    controller: App\Controller\UtilisateurController::deconnexion       
utilisateur_profil:
    path: /profil
    controller: App\Controller\UtilisateurController::profil   
admin:
    path: /admin
    controller: App\Controller\AdminController::index          